### ISSUE TITLE
underline dotted with exchange rates ?

### ISSUE THREAD

**Issue by cr0co** [joostdekeijzer/wp_eurofxref#3]
hello

how to disable the doted underline with exchange rates when i hover them ?

![help](https://user-images.githubusercontent.com/6071154/83166196-d72ebd00-a10e-11ea-8275-1cf2e6ee2c4d.png)

**Comment by joostdekeijzer** [comment]
See manual on https://wordpress.org/plugins/euro-fxref-currency-converter/

You can remove the lines by adding empty `to_style`. Can't remove the hover by default. You're welcome to make a PR.
